// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_dataflow_in_loop_TRA_1_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic a0_dataflow_in_loop_TRA_1_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic a0_dataflow_in_loop_TRA_1_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> a0_dataflow_in_loop_TRA_1_1::ap_ST_fsm_state1 = "1";
const sc_lv<32> a0_dataflow_in_loop_TRA_1_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool a0_dataflow_in_loop_TRA_1_1::ap_const_boolean_1 = true;

a0_dataflow_in_loop_TRA_1_1::a0_dataflow_in_loop_TRA_1_1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_training_id_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );

    SC_METHOD(thread_training_id_out1_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_training_id_out1_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_dout );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_training_id_out1_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_training_id_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_out_full_n );

    SC_METHOD(thread_training_id_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_dout );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_training_id_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_training_id_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( training_id_empty_n );
    sensitive << ( training_id_out_full_n );
    sensitive << ( training_id_out1_full_n );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_dataflow_in_loop_TRA_1_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, training_id_dout, "(port)training_id_dout");
    sc_trace(mVcdFile, training_id_empty_n, "(port)training_id_empty_n");
    sc_trace(mVcdFile, training_id_read, "(port)training_id_read");
    sc_trace(mVcdFile, training_id_out_din, "(port)training_id_out_din");
    sc_trace(mVcdFile, training_id_out_full_n, "(port)training_id_out_full_n");
    sc_trace(mVcdFile, training_id_out_write, "(port)training_id_out_write");
    sc_trace(mVcdFile, training_id_out1_din, "(port)training_id_out1_din");
    sc_trace(mVcdFile, training_id_out1_full_n, "(port)training_id_out1_full_n");
    sc_trace(mVcdFile, training_id_out1_write, "(port)training_id_out1_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, training_id_blk_n, "training_id_blk_n");
    sc_trace(mVcdFile, training_id_out_blk_n, "training_id_out_blk_n");
    sc_trace(mVcdFile, training_id_out1_blk_n, "training_id_out1_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

a0_dataflow_in_loop_TRA_1_1::~a0_dataflow_in_loop_TRA_1_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_ready() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        training_id_blk_n = training_id_empty_n.read();
    } else {
        training_id_blk_n = ap_const_logic_1;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_out1_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        training_id_out1_blk_n = training_id_out1_full_n.read();
    } else {
        training_id_out1_blk_n = ap_const_logic_1;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_out1_din() {
    training_id_out1_din = training_id_dout.read();
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_out1_write() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        training_id_out1_write = ap_const_logic_1;
    } else {
        training_id_out1_write = ap_const_logic_0;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        training_id_out_blk_n = training_id_out_full_n.read();
    } else {
        training_id_out_blk_n = ap_const_logic_1;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_out_din() {
    training_id_out_din = training_id_dout.read();
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_out_write() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        training_id_out_write = ap_const_logic_1;
    } else {
        training_id_out_write = ap_const_logic_0;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_training_id_read() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(training_id_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        training_id_read = ap_const_logic_1;
    } else {
        training_id_read = ap_const_logic_0;
    }
}

void a0_dataflow_in_loop_TRA_1_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

