# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3.xci
# IP: The module: 'zcu102_s00_regslice_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_s00_regslice_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_s00_regslice_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3.xci
# IP: The module: 'zcu102_s00_regslice_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_s00_regslice_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_s00_regslice_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
