#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("global_training_set_V_Addr_A", 32, hls_out, 0, "bram", "mem_address", 1),
	Port_Property("global_training_set_V_EN_A", 1, hls_out, 0, "bram", "mem_ce", 1),
	Port_Property("global_training_set_V_WEN_A", 32, hls_out, 0, "bram", "mem_we", 1),
	Port_Property("global_training_set_V_Din_A", 256, hls_out, 0, "bram", "mem_din", 1),
	Port_Property("global_training_set_V_Dout_A", 256, hls_in, 0, "bram", "mem_dout", 1),
	Port_Property("global_training_set_V_Clk_A", 1, hls_out, 0, "bram", "mem_clk", 1),
	Port_Property("global_training_set_V_Rst_A", 1, hls_out, 0, "bram", "mem_rst", 1),
	Port_Property("global_test_set_V_Addr_A", 32, hls_out, 1, "bram", "mem_address", 1),
	Port_Property("global_test_set_V_EN_A", 1, hls_out, 1, "bram", "mem_ce", 1),
	Port_Property("global_test_set_V_WEN_A", 32, hls_out, 1, "bram", "mem_we", 1),
	Port_Property("global_test_set_V_Din_A", 256, hls_out, 1, "bram", "mem_din", 1),
	Port_Property("global_test_set_V_Dout_A", 256, hls_in, 1, "bram", "mem_dout", 1),
	Port_Property("global_test_set_V_Clk_A", 1, hls_out, 1, "bram", "mem_clk", 1),
	Port_Property("global_test_set_V_Rst_A", 1, hls_out, 1, "bram", "mem_rst", 1),
	Port_Property("global_results_Addr_A", 32, hls_out, 2, "bram", "mem_address", 1),
	Port_Property("global_results_EN_A", 1, hls_out, 2, "bram", "mem_ce", 1),
	Port_Property("global_results_WEN_A", 1, hls_out, 2, "bram", "mem_we", 1),
	Port_Property("global_results_Din_A", 8, hls_out, 2, "bram", "mem_din", 1),
	Port_Property("global_results_Dout_A", 8, hls_in, 2, "bram", "mem_dout", 1),
	Port_Property("global_results_Clk_A", 1, hls_out, 2, "bram", "mem_clk", 1),
	Port_Property("global_results_Rst_A", 1, hls_out, 2, "bram", "mem_rst", 1),
	Port_Property("run", 32, hls_in, 3, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "DigitRec";
