# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param bd.ForceAppCoreUpgrade 1
set_param general.maxThreads 1
set_param project.loadTopLevelOOCConstrs 1
create_project -in_memory -part xczu9eg-ffvb1156-2-e
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_repo_paths {
  /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/iprepo/repo
  /apps/xilinx/2018.2/SDx/2018.2/data/ip/xilinx
  /apps/xilinx/2018.2/SDx/2018.2/data/cache/xilinx
  /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/.local/dsa/ipcache
  /apps/xilinx/2018.2/SDx/2018.2/data/ip
} [current_project]
set_property ip_output_repo /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/imports/hdl/zcu102_wrapper.v
add_files /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/zcu102.bd
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_ps_e_0/zcu102_ps_e_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_ps_e_0/zcu102_ps_e_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_clk_wiz_0_0/zcu102_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_clk_wiz_0_0/zcu102_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_clk_wiz_0_0/zcu102_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_0_0/zcu102_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_0_0/zcu102_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_0_0/zcu102_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_1_0/zcu102_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_1_0/zcu102_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_1_0/zcu102_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_2_0/zcu102_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_2_0/zcu102_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_2_0/zcu102_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_3_0/zcu102_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_3_0/zcu102_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_3_0/zcu102_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_4_0/zcu102_proc_sys_reset_4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_4_0/zcu102_proc_sys_reset_4_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_4_0/zcu102_proc_sys_reset_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_5_0/zcu102_proc_sys_reset_5_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_5_0/zcu102_proc_sys_reset_5_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_5_0/zcu102_proc_sys_reset_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_6_0/zcu102_proc_sys_reset_6_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_6_0/zcu102_proc_sys_reset_6_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_proc_sys_reset_6_0/zcu102_proc_sys_reset_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_dm_0_0/zcu102_dm_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_dm_0_0/zcu102_dm_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_dm_0_0/zcu102_dm_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_dm_1_0/zcu102_dm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_dm_1_0/zcu102_dm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_dm_1_0/zcu102_dm_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_rendering_1_0/constraints/a0_rendering_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_axis_dwc_dm_0_tx_0_0/zcu102_axis_dwc_dm_0_tx_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_axis_dwc_dm_1_rx_0_0/zcu102_axis_dwc_dm_1_rx_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_xbar_0/zcu102_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_2/zcu102_s00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_2/zcu102_s00_regslice_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_us_df_1/zcu102_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_us_df_1/zcu102_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_us_df_1/zcu102_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_1/zcu102_s00_regslice_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_1/zcu102_s00_regslice_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_us_df_0/zcu102_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_us_df_0/zcu102_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_us_df_0/zcu102_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_m02_regslice_0/zcu102_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_m02_regslice_0/zcu102_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_m01_regslice_0/zcu102_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_m01_regslice_0/zcu102_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_m00_regslice_0/zcu102_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_m00_regslice_0/zcu102_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_0/zcu102_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_regslice_0/zcu102_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_s00_data_fifo_0/zcu102_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_ds_0/zcu102_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_ds_0/zcu102_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_ds_0/zcu102_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/ip/zcu102_auto_pc_0/zcu102_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zcu102/zcu102_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/output/zcu102_ooc_copy.xdc
set_property used_in_implementation false [get_files /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/output/zcu102_ooc_copy.xdc]
set_property processing_order EARLY [get_files /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/3d-rendering/_sds/p0/vivado/output/zcu102_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top zcu102_wrapper -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zcu102_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zcu102_wrapper_utilization_synth.rpt -pb zcu102_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
