# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ylxiao_seas_upenn_edu/Roseetta/rosetta/spam-filter/_sds/p0/vivado/output/zcu102_ooc_copy.xdc

# Block Designs: bd/zcu102/zcu102.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102 || ORIG_REF_NAME==zcu102} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_ps_e_0/zcu102_ps_e_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_ps_e_0 || ORIG_REF_NAME==zcu102_ps_e_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_clk_wiz_0_0/zcu102_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_clk_wiz_0_0 || ORIG_REF_NAME==zcu102_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_0_0/zcu102_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_0_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_1_0/zcu102_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_1_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_2_0/zcu102_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_2_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_3_0/zcu102_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_3_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_4_0/zcu102_proc_sys_reset_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_4_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_5_0/zcu102_proc_sys_reset_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_5_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_proc_sys_reset_6_0/zcu102_proc_sys_reset_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_proc_sys_reset_6_0 || ORIG_REF_NAME==zcu102_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_xlconcat_0_0/zcu102_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_xlconcat_0_0 || ORIG_REF_NAME==zcu102_xlconcat_0_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_xlconcat_1_0/zcu102_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_xlconcat_1_0 || ORIG_REF_NAME==zcu102_xlconcat_1_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_dm_0_0/zcu102_dm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_dm_0_0 || ORIG_REF_NAME==zcu102_dm_0_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_SgdLR_1_0/zcu102_SgdLR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_SgdLR_1_0 || ORIG_REF_NAME==zcu102_SgdLR_1_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_SgdLR_1_if_0/zcu102_SgdLR_1_if_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_SgdLR_1_if_0 || ORIG_REF_NAME==zcu102_SgdLR_1_if_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_axi_ic_ps_e_M_AXI_HPM0_FPD_0/zcu102_axi_ic_ps_e_M_AXI_HPM0_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_axi_ic_ps_e_M_AXI_HPM0_FPD_0 || ORIG_REF_NAME==zcu102_axi_ic_ps_e_M_AXI_HPM0_FPD_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_axi_ic_ps_e_S_AXI_HP1_FPD_0/zcu102_axi_ic_ps_e_S_AXI_HP1_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_axi_ic_ps_e_S_AXI_HP1_FPD_0 || ORIG_REF_NAME==zcu102_axi_ic_ps_e_S_AXI_HP1_FPD_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_axi_ic_ps_e_S_AXI_HP0_FPD_0/zcu102_axi_ic_ps_e_S_AXI_HP0_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_axi_ic_ps_e_S_AXI_HP0_FPD_0 || ORIG_REF_NAME==zcu102_axi_ic_ps_e_S_AXI_HP0_FPD_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_axi_ic_ps_e_S_AXI_HP2_FPD_0/zcu102_axi_ic_ps_e_S_AXI_HP2_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_axi_ic_ps_e_S_AXI_HP2_FPD_0 || ORIG_REF_NAME==zcu102_axi_ic_ps_e_S_AXI_HP2_FPD_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_sgdma2axis_dm_0_0/zcu102_sgdma2axis_dm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_sgdma2axis_dm_0_0 || ORIG_REF_NAME==zcu102_sgdma2axis_dm_0_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_axis_ic_dm_0_0/zcu102_axis_ic_dm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_axis_ic_dm_0_0 || ORIG_REF_NAME==zcu102_axis_ic_dm_0_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_sds_irq_const_0/zcu102_sds_irq_const_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_sds_irq_const_0 || ORIG_REF_NAME==zcu102_sds_irq_const_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_xbar_1/zcu102_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_xbar_1 || ORIG_REF_NAME==zcu102_xbar_1} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_xbar_0/zcu102_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_xbar_0 || ORIG_REF_NAME==zcu102_xbar_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_regslice_4/zcu102_s00_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_regslice_4 || ORIG_REF_NAME==zcu102_s00_regslice_4} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_ss_slid_0/zcu102_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_ss_slid_0 || ORIG_REF_NAME==zcu102_auto_ss_slid_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_regslice_3/zcu102_s00_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_regslice_3 || ORIG_REF_NAME==zcu102_s00_regslice_3} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_us_df_3/zcu102_auto_us_df_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_us_df_3 || ORIG_REF_NAME==zcu102_auto_us_df_3} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_regslice_2/zcu102_s00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_regslice_2 || ORIG_REF_NAME==zcu102_s00_regslice_2} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_us_df_2/zcu102_auto_us_df_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_us_df_2 || ORIG_REF_NAME==zcu102_auto_us_df_2} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_mmu_0/zcu102_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_mmu_0 || ORIG_REF_NAME==zcu102_s00_mmu_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s01_mmu_0/zcu102_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s01_mmu_0 || ORIG_REF_NAME==zcu102_s01_mmu_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_m00_data_fifo_0/zcu102_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_m00_data_fifo_0 || ORIG_REF_NAME==zcu102_m00_data_fifo_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_m00_regslice_1/zcu102_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_m00_regslice_1 || ORIG_REF_NAME==zcu102_m00_regslice_1} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s01_regslice_0/zcu102_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s01_regslice_0 || ORIG_REF_NAME==zcu102_s01_regslice_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_us_df_1/zcu102_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_us_df_1 || ORIG_REF_NAME==zcu102_auto_us_df_1} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_regslice_1/zcu102_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_regslice_1 || ORIG_REF_NAME==zcu102_s00_regslice_1} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_us_df_0/zcu102_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_us_df_0 || ORIG_REF_NAME==zcu102_auto_us_df_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_m01_regslice_0/zcu102_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_m01_regslice_0 || ORIG_REF_NAME==zcu102_m01_regslice_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_m00_regslice_0/zcu102_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_m00_regslice_0 || ORIG_REF_NAME==zcu102_m00_regslice_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_regslice_0/zcu102_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_regslice_0 || ORIG_REF_NAME==zcu102_s00_regslice_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_s00_data_fifo_0/zcu102_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_s00_data_fifo_0 || ORIG_REF_NAME==zcu102_s00_data_fifo_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_ds_0/zcu102_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_ds_0 || ORIG_REF_NAME==zcu102_auto_ds_0} -quiet] -quiet

# IP: bd/zcu102/ip/zcu102_auto_pc_0/zcu102_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_auto_pc_0 || ORIG_REF_NAME==zcu102_auto_pc_0} -quiet] -quiet

# XDC: bd/zcu102/zcu102_ooc.xdc
