// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_Loop_FRAMES_CP_OUTER.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic a0_Loop_FRAMES_CP_OUTER::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic a0_Loop_FRAMES_CP_OUTER::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> a0_Loop_FRAMES_CP_OUTER::ap_ST_fsm_state1 = "1";
const sc_lv<3> a0_Loop_FRAMES_CP_OUTER::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> a0_Loop_FRAMES_CP_OUTER::ap_ST_fsm_state17 = "100";
const bool a0_Loop_FRAMES_CP_OUTER::ap_const_boolean_1 = true;
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_1 = "1";
const bool a0_Loop_FRAMES_CP_OUTER::ap_const_boolean_0 = false;
const sc_lv<1> a0_Loop_FRAMES_CP_OUTER::ap_const_lv1_0 = "0";
const sc_lv<1> a0_Loop_FRAMES_CP_OUTER::ap_const_lv1_1 = "1";
const sc_lv<19> a0_Loop_FRAMES_CP_OUTER::ap_const_lv19_0 = "0000000000000000000";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_437F0000 = "1000011011111110000000000000000";
const sc_lv<19> a0_Loop_FRAMES_CP_OUTER::ap_const_lv19_6D000 = "1101101000000000000";
const sc_lv<19> a0_Loop_FRAMES_CP_OUTER::ap_const_lv19_1 = "1";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_8 = "1000";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_F = "1111";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_10 = "10000";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_17 = "10111";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_18 = "11000";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_1F = "11111";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_20 = "100000";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_27 = "100111";
const sc_lv<32> a0_Loop_FRAMES_CP_OUTER::ap_const_lv32_2 = "10";

a0_Loop_FRAMES_CP_OUTER::a0_Loop_FRAMES_CP_OUTER(sc_module_name name) : sc_module(name), mVcdFile(0) {
    optical_flow_fdivbkb_U1 = new a0_optical_flow_fdivbkb<1,9,32,32,32>("optical_flow_fdivbkb_U1");
    optical_flow_fdivbkb_U1->clk(ap_clk);
    optical_flow_fdivbkb_U1->reset(ap_rst);
    optical_flow_fdivbkb_U1->din0(tmp_46_i_i_reg_356);
    optical_flow_fdivbkb_U1->din1(ap_var_for_const0);
    optical_flow_fdivbkb_U1->ce(grp_fu_201_ce);
    optical_flow_fdivbkb_U1->dout(grp_fu_201_p2);
    optical_flow_fdivbkb_U2 = new a0_optical_flow_fdivbkb<1,9,32,32,32>("optical_flow_fdivbkb_U2");
    optical_flow_fdivbkb_U2->clk(ap_clk);
    optical_flow_fdivbkb_U2->reset(ap_rst);
    optical_flow_fdivbkb_U2->din0(tmp_48_i_i_reg_361);
    optical_flow_fdivbkb_U2->din1(ap_var_for_const0);
    optical_flow_fdivbkb_U2->ce(grp_fu_206_ce);
    optical_flow_fdivbkb_U2->dout(grp_fu_206_p2);
    optical_flow_fdivbkb_U3 = new a0_optical_flow_fdivbkb<1,9,32,32,32>("optical_flow_fdivbkb_U3");
    optical_flow_fdivbkb_U3->clk(ap_clk);
    optical_flow_fdivbkb_U3->reset(ap_rst);
    optical_flow_fdivbkb_U3->din0(tmp_50_i_i_reg_366);
    optical_flow_fdivbkb_U3->din1(ap_var_for_const0);
    optical_flow_fdivbkb_U3->ce(grp_fu_211_ce);
    optical_flow_fdivbkb_U3->dout(grp_fu_211_p2);
    optical_flow_fdivbkb_U4 = new a0_optical_flow_fdivbkb<1,9,32,32,32>("optical_flow_fdivbkb_U4");
    optical_flow_fdivbkb_U4->clk(ap_clk);
    optical_flow_fdivbkb_U4->reset(ap_rst);
    optical_flow_fdivbkb_U4->din0(tmp_52_i_i_reg_371);
    optical_flow_fdivbkb_U4->din1(ap_var_for_const0);
    optical_flow_fdivbkb_U4->ce(grp_fu_216_ce);
    optical_flow_fdivbkb_U4->dout(grp_fu_216_p2);
    optical_flow_fdivbkb_U5 = new a0_optical_flow_fdivbkb<1,9,32,32,32>("optical_flow_fdivbkb_U5");
    optical_flow_fdivbkb_U5->clk(ap_clk);
    optical_flow_fdivbkb_U5->reset(ap_rst);
    optical_flow_fdivbkb_U5->din0(tmp_54_i_i_reg_376);
    optical_flow_fdivbkb_U5->din1(ap_var_for_const0);
    optical_flow_fdivbkb_U5->ce(grp_fu_221_ce);
    optical_flow_fdivbkb_U5->dout(grp_fu_221_p2);
    optical_flow_uitocud_U6 = new a0_optical_flow_uitocud<1,4,32,32>("optical_flow_uitocud_U6");
    optical_flow_uitocud_U6->clk(ap_clk);
    optical_flow_uitocud_U6->reset(ap_rst);
    optical_flow_uitocud_U6->din0(grp_fu_226_p0);
    optical_flow_uitocud_U6->ce(grp_fu_226_ce);
    optical_flow_uitocud_U6->dout(grp_fu_226_p1);
    optical_flow_uitocud_U7 = new a0_optical_flow_uitocud<1,4,32,32>("optical_flow_uitocud_U7");
    optical_flow_uitocud_U7->clk(ap_clk);
    optical_flow_uitocud_U7->reset(ap_rst);
    optical_flow_uitocud_U7->din0(grp_fu_229_p0);
    optical_flow_uitocud_U7->ce(grp_fu_229_ce);
    optical_flow_uitocud_U7->dout(grp_fu_229_p1);
    optical_flow_uitocud_U8 = new a0_optical_flow_uitocud<1,4,32,32>("optical_flow_uitocud_U8");
    optical_flow_uitocud_U8->clk(ap_clk);
    optical_flow_uitocud_U8->reset(ap_rst);
    optical_flow_uitocud_U8->din0(grp_fu_232_p0);
    optical_flow_uitocud_U8->ce(grp_fu_232_ce);
    optical_flow_uitocud_U8->dout(grp_fu_232_p1);
    optical_flow_uitocud_U9 = new a0_optical_flow_uitocud<1,4,32,32>("optical_flow_uitocud_U9");
    optical_flow_uitocud_U9->clk(ap_clk);
    optical_flow_uitocud_U9->reset(ap_rst);
    optical_flow_uitocud_U9->din0(grp_fu_235_p0);
    optical_flow_uitocud_U9->ce(grp_fu_235_ce);
    optical_flow_uitocud_U9->dout(grp_fu_235_p1);
    optical_flow_uitocud_U10 = new a0_optical_flow_uitocud<1,4,32,32>("optical_flow_uitocud_U10");
    optical_flow_uitocud_U10->clk(ap_clk);
    optical_flow_uitocud_U10->reset(ap_rst);
    optical_flow_uitocud_U10->din0(grp_fu_238_p0);
    optical_flow_uitocud_U10->ce(grp_fu_238_ce);
    optical_flow_uitocud_U10->dout(grp_fu_238_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( frames_V_empty_n );
    sensitive << ( frame1_a_full_n );
    sensitive << ( frame2_a_full_n );
    sensitive << ( frame3_a_full_n );
    sensitive << ( frame3_b_full_n );
    sensitive << ( frame4_a_full_n );
    sensitive << ( frame5_a_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_flatten_reg_322 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( frames_V_empty_n );
    sensitive << ( frame1_a_full_n );
    sensitive << ( frame2_a_full_n );
    sensitive << ( frame3_a_full_n );
    sensitive << ( frame3_b_full_n );
    sensitive << ( frame4_a_full_n );
    sensitive << ( frame5_a_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_flatten_reg_322 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( frames_V_empty_n );
    sensitive << ( frame1_a_full_n );
    sensitive << ( frame2_a_full_n );
    sensitive << ( frame3_a_full_n );
    sensitive << ( frame3_b_full_n );
    sensitive << ( frame4_a_full_n );
    sensitive << ( frame5_a_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_flatten_reg_322 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter14);
    sensitive << ( frame1_a_full_n );
    sensitive << ( frame2_a_full_n );
    sensitive << ( frame3_a_full_n );
    sensitive << ( frame3_b_full_n );
    sensitive << ( frame4_a_full_n );
    sensitive << ( frame5_a_full_n );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( frames_V_empty_n );
    sensitive << ( exitcond_flatten_reg_322 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten_fu_241_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_exitcond_flatten_fu_241_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_190 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_frame1_a_blk_n);
    sensitive << ( frame1_a_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_frame1_a_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( tmp_47_i_i_reg_381 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_frame1_a_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_frame2_a_blk_n);
    sensitive << ( frame2_a_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_frame2_a_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( tmp_49_i_i_reg_386 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_frame2_a_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_frame3_a_blk_n);
    sensitive << ( frame3_a_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_frame3_a_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( tmp_51_i_i_reg_391 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_frame3_a_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_frame3_b_blk_n);
    sensitive << ( frame3_b_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_frame3_b_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( tmp_51_i_i_reg_391 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_frame3_b_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_frame4_a_blk_n);
    sensitive << ( frame4_a_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_frame4_a_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( tmp_53_i_i_reg_397 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_frame4_a_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_frame5_a_blk_n);
    sensitive << ( frame5_a_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );

    SC_METHOD(thread_frame5_a_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( tmp_55_i_i_reg_402 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_frame5_a_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_reg_322_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_frames_V_blk_n);
    sensitive << ( frames_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_flatten_reg_322 );

    SC_METHOD(thread_frames_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_flatten_reg_322 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_201_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_206_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_211_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_216_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_221_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_226_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_226_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_fu_253_p1 );

    SC_METHOD(thread_grp_fu_229_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_229_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_Result_1_i_i_fu_262_p4 );

    SC_METHOD(thread_grp_fu_232_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_232_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_Result_2_i_i_fu_277_p4 );

    SC_METHOD(thread_grp_fu_235_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_235_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_Result_3_i_i_fu_292_p4 );

    SC_METHOD(thread_grp_fu_238_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_238_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_Result_4_i_i_fu_307_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_247_p2);
    sensitive << ( indvar_flatten_reg_190 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_p_Result_1_i_i_fu_262_p4);
    sensitive << ( frames_V_dout );

    SC_METHOD(thread_p_Result_2_i_i_fu_277_p4);
    sensitive << ( frames_V_dout );

    SC_METHOD(thread_p_Result_3_i_i_fu_292_p4);
    sensitive << ( frames_V_dout );

    SC_METHOD(thread_p_Result_4_i_i_fu_307_p4);
    sensitive << ( frames_V_dout );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_fu_253_p1);
    sensitive << ( frames_V_dout );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( exitcond_flatten_fu_241_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter13 );

    SC_THREAD(thread_ap_var_for_const0);

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_Loop_FRAMES_CP_OUTER_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, frames_V_dout, "(port)frames_V_dout");
    sc_trace(mVcdFile, frames_V_empty_n, "(port)frames_V_empty_n");
    sc_trace(mVcdFile, frames_V_read, "(port)frames_V_read");
    sc_trace(mVcdFile, frame1_a_din, "(port)frame1_a_din");
    sc_trace(mVcdFile, frame1_a_full_n, "(port)frame1_a_full_n");
    sc_trace(mVcdFile, frame1_a_write, "(port)frame1_a_write");
    sc_trace(mVcdFile, frame2_a_din, "(port)frame2_a_din");
    sc_trace(mVcdFile, frame2_a_full_n, "(port)frame2_a_full_n");
    sc_trace(mVcdFile, frame2_a_write, "(port)frame2_a_write");
    sc_trace(mVcdFile, frame3_a_din, "(port)frame3_a_din");
    sc_trace(mVcdFile, frame3_a_full_n, "(port)frame3_a_full_n");
    sc_trace(mVcdFile, frame3_a_write, "(port)frame3_a_write");
    sc_trace(mVcdFile, frame3_b_din, "(port)frame3_b_din");
    sc_trace(mVcdFile, frame3_b_full_n, "(port)frame3_b_full_n");
    sc_trace(mVcdFile, frame3_b_write, "(port)frame3_b_write");
    sc_trace(mVcdFile, frame4_a_din, "(port)frame4_a_din");
    sc_trace(mVcdFile, frame4_a_full_n, "(port)frame4_a_full_n");
    sc_trace(mVcdFile, frame4_a_write, "(port)frame4_a_write");
    sc_trace(mVcdFile, frame5_a_din, "(port)frame5_a_din");
    sc_trace(mVcdFile, frame5_a_full_n, "(port)frame5_a_full_n");
    sc_trace(mVcdFile, frame5_a_write, "(port)frame5_a_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, frames_V_blk_n, "frames_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_flatten_reg_322, "exitcond_flatten_reg_322");
    sc_trace(mVcdFile, frame1_a_blk_n, "frame1_a_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter13_reg, "exitcond_flatten_reg_322_pp0_iter13_reg");
    sc_trace(mVcdFile, frame2_a_blk_n, "frame2_a_blk_n");
    sc_trace(mVcdFile, frame3_a_blk_n, "frame3_a_blk_n");
    sc_trace(mVcdFile, frame3_b_blk_n, "frame3_b_blk_n");
    sc_trace(mVcdFile, frame4_a_blk_n, "frame4_a_blk_n");
    sc_trace(mVcdFile, frame5_a_blk_n, "frame5_a_blk_n");
    sc_trace(mVcdFile, indvar_flatten_reg_190, "indvar_flatten_reg_190");
    sc_trace(mVcdFile, exitcond_flatten_fu_241_p2, "exitcond_flatten_fu_241_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter13, "ap_block_state15_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter14, "ap_block_state16_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter1_reg, "exitcond_flatten_reg_322_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter2_reg, "exitcond_flatten_reg_322_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter3_reg, "exitcond_flatten_reg_322_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter4_reg, "exitcond_flatten_reg_322_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter5_reg, "exitcond_flatten_reg_322_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter6_reg, "exitcond_flatten_reg_322_pp0_iter6_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter7_reg, "exitcond_flatten_reg_322_pp0_iter7_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter8_reg, "exitcond_flatten_reg_322_pp0_iter8_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter9_reg, "exitcond_flatten_reg_322_pp0_iter9_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter10_reg, "exitcond_flatten_reg_322_pp0_iter10_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter11_reg, "exitcond_flatten_reg_322_pp0_iter11_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_322_pp0_iter12_reg, "exitcond_flatten_reg_322_pp0_iter12_reg");
    sc_trace(mVcdFile, indvar_flatten_next_fu_247_p2, "indvar_flatten_next_fu_247_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, grp_fu_226_p1, "grp_fu_226_p1");
    sc_trace(mVcdFile, tmp_46_i_i_reg_356, "tmp_46_i_i_reg_356");
    sc_trace(mVcdFile, grp_fu_229_p1, "grp_fu_229_p1");
    sc_trace(mVcdFile, tmp_48_i_i_reg_361, "tmp_48_i_i_reg_361");
    sc_trace(mVcdFile, grp_fu_232_p1, "grp_fu_232_p1");
    sc_trace(mVcdFile, tmp_50_i_i_reg_366, "tmp_50_i_i_reg_366");
    sc_trace(mVcdFile, grp_fu_235_p1, "grp_fu_235_p1");
    sc_trace(mVcdFile, tmp_52_i_i_reg_371, "tmp_52_i_i_reg_371");
    sc_trace(mVcdFile, grp_fu_238_p1, "grp_fu_238_p1");
    sc_trace(mVcdFile, tmp_54_i_i_reg_376, "tmp_54_i_i_reg_376");
    sc_trace(mVcdFile, grp_fu_201_p2, "grp_fu_201_p2");
    sc_trace(mVcdFile, tmp_47_i_i_reg_381, "tmp_47_i_i_reg_381");
    sc_trace(mVcdFile, grp_fu_206_p2, "grp_fu_206_p2");
    sc_trace(mVcdFile, tmp_49_i_i_reg_386, "tmp_49_i_i_reg_386");
    sc_trace(mVcdFile, grp_fu_211_p2, "grp_fu_211_p2");
    sc_trace(mVcdFile, tmp_51_i_i_reg_391, "tmp_51_i_i_reg_391");
    sc_trace(mVcdFile, grp_fu_216_p2, "grp_fu_216_p2");
    sc_trace(mVcdFile, tmp_53_i_i_reg_397, "tmp_53_i_i_reg_397");
    sc_trace(mVcdFile, grp_fu_221_p2, "grp_fu_221_p2");
    sc_trace(mVcdFile, tmp_55_i_i_reg_402, "tmp_55_i_i_reg_402");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_226_p0, "grp_fu_226_p0");
    sc_trace(mVcdFile, grp_fu_229_p0, "grp_fu_229_p0");
    sc_trace(mVcdFile, grp_fu_232_p0, "grp_fu_232_p0");
    sc_trace(mVcdFile, grp_fu_235_p0, "grp_fu_235_p0");
    sc_trace(mVcdFile, grp_fu_238_p0, "grp_fu_238_p0");
    sc_trace(mVcdFile, tmp_fu_253_p1, "tmp_fu_253_p1");
    sc_trace(mVcdFile, p_Result_1_i_i_fu_262_p4, "p_Result_1_i_i_fu_262_p4");
    sc_trace(mVcdFile, p_Result_2_i_i_fu_277_p4, "p_Result_2_i_i_fu_277_p4");
    sc_trace(mVcdFile, p_Result_3_i_i_fu_292_p4, "p_Result_3_i_i_fu_292_p4");
    sc_trace(mVcdFile, p_Result_4_i_i_fu_307_p4, "p_Result_4_i_i_fu_307_p4");
    sc_trace(mVcdFile, grp_fu_201_ce, "grp_fu_201_ce");
    sc_trace(mVcdFile, grp_fu_206_ce, "grp_fu_206_ce");
    sc_trace(mVcdFile, grp_fu_211_ce, "grp_fu_211_ce");
    sc_trace(mVcdFile, grp_fu_216_ce, "grp_fu_216_ce");
    sc_trace(mVcdFile, grp_fu_221_ce, "grp_fu_221_ce");
    sc_trace(mVcdFile, grp_fu_226_ce, "grp_fu_226_ce");
    sc_trace(mVcdFile, grp_fu_229_ce, "grp_fu_229_ce");
    sc_trace(mVcdFile, grp_fu_232_ce, "grp_fu_232_ce");
    sc_trace(mVcdFile, grp_fu_235_ce, "grp_fu_235_ce");
    sc_trace(mVcdFile, grp_fu_238_ce, "grp_fu_238_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

a0_Loop_FRAMES_CP_OUTER::~a0_Loop_FRAMES_CP_OUTER() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete optical_flow_fdivbkb_U1;
    delete optical_flow_fdivbkb_U2;
    delete optical_flow_fdivbkb_U3;
    delete optical_flow_fdivbkb_U4;
    delete optical_flow_fdivbkb_U5;
    delete optical_flow_uitocud_U6;
    delete optical_flow_uitocud_U7;
    delete optical_flow_uitocud_U8;
    delete optical_flow_uitocud_U9;
    delete optical_flow_uitocud_U10;
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_437F0000;
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter14 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_241_p2.read()))) {
        indvar_flatten_reg_190 = indvar_flatten_next_fu_247_p2.read();
    } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvar_flatten_reg_190 = ap_const_lv19_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten_reg_322 = exitcond_flatten_fu_241_p2.read();
        exitcond_flatten_reg_322_pp0_iter1_reg = exitcond_flatten_reg_322.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond_flatten_reg_322_pp0_iter10_reg = exitcond_flatten_reg_322_pp0_iter9_reg.read();
        exitcond_flatten_reg_322_pp0_iter11_reg = exitcond_flatten_reg_322_pp0_iter10_reg.read();
        exitcond_flatten_reg_322_pp0_iter12_reg = exitcond_flatten_reg_322_pp0_iter11_reg.read();
        exitcond_flatten_reg_322_pp0_iter13_reg = exitcond_flatten_reg_322_pp0_iter12_reg.read();
        exitcond_flatten_reg_322_pp0_iter2_reg = exitcond_flatten_reg_322_pp0_iter1_reg.read();
        exitcond_flatten_reg_322_pp0_iter3_reg = exitcond_flatten_reg_322_pp0_iter2_reg.read();
        exitcond_flatten_reg_322_pp0_iter4_reg = exitcond_flatten_reg_322_pp0_iter3_reg.read();
        exitcond_flatten_reg_322_pp0_iter5_reg = exitcond_flatten_reg_322_pp0_iter4_reg.read();
        exitcond_flatten_reg_322_pp0_iter6_reg = exitcond_flatten_reg_322_pp0_iter5_reg.read();
        exitcond_flatten_reg_322_pp0_iter7_reg = exitcond_flatten_reg_322_pp0_iter6_reg.read();
        exitcond_flatten_reg_322_pp0_iter8_reg = exitcond_flatten_reg_322_pp0_iter7_reg.read();
        exitcond_flatten_reg_322_pp0_iter9_reg = exitcond_flatten_reg_322_pp0_iter8_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter3_reg.read()))) {
        tmp_46_i_i_reg_356 = grp_fu_226_p1.read();
        tmp_48_i_i_reg_361 = grp_fu_229_p1.read();
        tmp_50_i_i_reg_366 = grp_fu_232_p1.read();
        tmp_52_i_i_reg_371 = grp_fu_235_p1.read();
        tmp_54_i_i_reg_376 = grp_fu_238_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter12_reg.read()))) {
        tmp_47_i_i_reg_381 = grp_fu_201_p2.read();
        tmp_49_i_i_reg_386 = grp_fu_206_p2.read();
        tmp_51_i_i_reg_391 = grp_fu_211_p2.read();
        tmp_53_i_i_reg_397 = grp_fu_216_p2.read();
        tmp_55_i_i_reg_402 = grp_fu_221_p2.read();
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[2];
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(exitcond_flatten_reg_322.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frames_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame1_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame2_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame3_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame3_b_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame4_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame5_a_full_n.read())))));
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(exitcond_flatten_reg_322.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frames_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame1_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame2_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame3_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame3_b_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame4_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame5_a_full_n.read())))));
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(exitcond_flatten_reg_322.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frames_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame1_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame2_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame3_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame3_b_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame4_a_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, frame5_a_full_n.read())))));
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state15_pp0_stage0_iter13() {
    ap_block_state15_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state16_pp0_stage0_iter14() {
    ap_block_state16_pp0_stage0_iter14 = ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frame1_a_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frame2_a_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frame3_a_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frame3_b_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frame4_a_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, frame5_a_full_n.read())));
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(exitcond_flatten_reg_322.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, frames_V_empty_n.read()));
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten_fu_241_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_exitcond_flatten_fu_241_p2() {
    exitcond_flatten_fu_241_p2 = (!indvar_flatten_reg_190.read().is_01() || !ap_const_lv19_6D000.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_190.read() == ap_const_lv19_6D000);
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame1_a_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()))) {
        frame1_a_blk_n = frame1_a_full_n.read();
    } else {
        frame1_a_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame1_a_din() {
    frame1_a_din = tmp_47_i_i_reg_381.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame1_a_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frame1_a_write = ap_const_logic_1;
    } else {
        frame1_a_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame2_a_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()))) {
        frame2_a_blk_n = frame2_a_full_n.read();
    } else {
        frame2_a_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame2_a_din() {
    frame2_a_din = tmp_49_i_i_reg_386.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame2_a_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frame2_a_write = ap_const_logic_1;
    } else {
        frame2_a_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame3_a_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()))) {
        frame3_a_blk_n = frame3_a_full_n.read();
    } else {
        frame3_a_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame3_a_din() {
    frame3_a_din = tmp_51_i_i_reg_391.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame3_a_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frame3_a_write = ap_const_logic_1;
    } else {
        frame3_a_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame3_b_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()))) {
        frame3_b_blk_n = frame3_b_full_n.read();
    } else {
        frame3_b_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame3_b_din() {
    frame3_b_din = tmp_51_i_i_reg_391.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame3_b_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frame3_b_write = ap_const_logic_1;
    } else {
        frame3_b_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame4_a_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()))) {
        frame4_a_blk_n = frame4_a_full_n.read();
    } else {
        frame4_a_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame4_a_din() {
    frame4_a_din = tmp_53_i_i_reg_397.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame4_a_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frame4_a_write = ap_const_logic_1;
    } else {
        frame4_a_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame5_a_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()))) {
        frame5_a_blk_n = frame5_a_full_n.read();
    } else {
        frame5_a_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame5_a_din() {
    frame5_a_din = tmp_55_i_i_reg_402.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_frame5_a_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_322_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frame5_a_write = ap_const_logic_1;
    } else {
        frame5_a_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frames_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_322.read(), ap_const_lv1_0))) {
        frames_V_blk_n = frames_V_empty_n.read();
    } else {
        frames_V_blk_n = ap_const_logic_1;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_frames_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_322.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        frames_V_read = ap_const_logic_1;
    } else {
        frames_V_read = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_201_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_201_ce = ap_const_logic_1;
    } else {
        grp_fu_201_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_206_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_206_ce = ap_const_logic_1;
    } else {
        grp_fu_206_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_211_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_211_ce = ap_const_logic_1;
    } else {
        grp_fu_211_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_216_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_216_ce = ap_const_logic_1;
    } else {
        grp_fu_216_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_221_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_221_ce = ap_const_logic_1;
    } else {
        grp_fu_221_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_226_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_226_ce = ap_const_logic_1;
    } else {
        grp_fu_226_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_226_p0() {
    grp_fu_226_p0 = esl_zext<32,8>(tmp_fu_253_p1.read());
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_229_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_229_ce = ap_const_logic_1;
    } else {
        grp_fu_229_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_229_p0() {
    grp_fu_229_p0 = esl_zext<32,8>(p_Result_1_i_i_fu_262_p4.read());
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_232_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_232_ce = ap_const_logic_1;
    } else {
        grp_fu_232_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_232_p0() {
    grp_fu_232_p0 = esl_zext<32,8>(p_Result_2_i_i_fu_277_p4.read());
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_235_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_235_ce = ap_const_logic_1;
    } else {
        grp_fu_235_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_235_p0() {
    grp_fu_235_p0 = esl_zext<32,8>(p_Result_3_i_i_fu_292_p4.read());
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_238_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_238_ce = ap_const_logic_1;
    } else {
        grp_fu_238_ce = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_grp_fu_238_p0() {
    grp_fu_238_p0 = esl_zext<32,8>(p_Result_4_i_i_fu_307_p4.read());
}

void a0_Loop_FRAMES_CP_OUTER::thread_indvar_flatten_next_fu_247_p2() {
    indvar_flatten_next_fu_247_p2 = (!indvar_flatten_reg_190.read().is_01() || !ap_const_lv19_1.is_01())? sc_lv<19>(): (sc_biguint<19>(indvar_flatten_reg_190.read()) + sc_biguint<19>(ap_const_lv19_1));
}

void a0_Loop_FRAMES_CP_OUTER::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_p_Result_1_i_i_fu_262_p4() {
    p_Result_1_i_i_fu_262_p4 = frames_V_dout.read().range(15, 8);
}

void a0_Loop_FRAMES_CP_OUTER::thread_p_Result_2_i_i_fu_277_p4() {
    p_Result_2_i_i_fu_277_p4 = frames_V_dout.read().range(23, 16);
}

void a0_Loop_FRAMES_CP_OUTER::thread_p_Result_3_i_i_fu_292_p4() {
    p_Result_3_i_i_fu_292_p4 = frames_V_dout.read().range(31, 24);
}

void a0_Loop_FRAMES_CP_OUTER::thread_p_Result_4_i_i_fu_307_p4() {
    p_Result_4_i_i_fu_307_p4 = frames_V_dout.read().range(39, 32);
}

void a0_Loop_FRAMES_CP_OUTER::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_start_out() {
    start_out = real_start.read();
}

void a0_Loop_FRAMES_CP_OUTER::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void a0_Loop_FRAMES_CP_OUTER::thread_tmp_fu_253_p1() {
    tmp_fu_253_p1 = frames_V_dout.read().range(8-1, 0);
}

void a0_Loop_FRAMES_CP_OUTER::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(exitcond_flatten_fu_241_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter13.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter13.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter14.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(exitcond_flatten_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

